// 1-frameworks/vue/button/button.vue
<template>
  <button v-bind:class="classObject" v-on:click="$emit('click')">
    <slot></slot>
  </button>
</template>

<script>
export default {
  name: "Button",
  props: {
    color: {
      type: String,
      required: true
    }
  },
  computed: {
    classObject() {
      return {
        color: this.color
      };
    }
  }
};
</script>

<style scoped>
.success {
  background-color: green;
}

.warn {
  background-color: yellow;
}

.danger {
  background-color: red;
}
</style>

// 1-frameworks/react/button/button.tsx
import * as React from 'react'

export interface ButtonProps {
  color: 'success' | 'warn' | 'danger'
  onClick: () => void
}

export const Button: React.SFC<ButtonProps> = ({ color, onClick, children }) => (
  <button
    style={{ backgroundColor: getBackgroundColor(color) }}
    onClick={onClick}
  >
    {children}
  </button>
)

function getBackgroundColor(color: 'success' | 'warn' | 'danger') {
  return color === 'success' ? 'green' : color === 'danger' ? 'yellow' : 'red'
}




































export type SuccessButtonProps = Omit<ButtonProps, 'color'>
export const SuccessButton: React.SFC<SuccessButtonProps> = props =>
  <Button color='success' {...props} />
