// 1-frameworks/react/usage.tsx
import * as React from 'react'
import { Button, SuccessButton } from './button/button';

export function render() {
  return (
    <>
      <Button
        color='success'
        onClick={() => window.alert('button 1 clicked')}
      >
        Button 1
      </Button>

      <SuccessButton
        onClick={() => window.alert('button 2 clicked')}
      >
        Button 2
      </SuccessButton>
    </>
  )
}

// 1-frameworks/vue/usage.vue
<template>
  <div>
    <Button color="success" v-on:click="onClick(1)"></Button>
    <SuccessButton v-on:click="onClick(2)"></SuccessButton>
  </div>
</template>

<script lang="ts">
import Button from "./button/button.vue";
import SuccessButton from "./button/success-button.vue";

export default {
  components: {
    Button,
    SuccessButton
  },
  methods: {
    onClick(index: number) {
      alert(`button ${index} clicked`)
    }
  }
};
</script>
